### DISCUSSION TITLE
How to get regreet to read config file?

### DISCUSSION THREAD

**Discussion by 10leej** [rharish101/ReGreet#22] [Q&A] [answered]
So I'm loading regreet via greetd and cage in /etc/greetd/config.toml I'm calling 

`command = " cage -s -- regreet --config /etc/greetd/regreet.toml"`

however all I'm getting is the blinding light theme

```toml

# SPDX-FileCopyrightText: 2022 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[background]
# Path to the background image
path = "/usr/share/backrounds/Desktop-Backround.png""

# How the background image covers the screen if the aspect ratio doesn't match
# Available values: "Fill", "Contain", "Cover", "ScaleDown"
# Refer to: https://docs.gtk.org/gtk4/enum.ContentFit.html
# NOTE: This is ignored if ReGreet isn't compiled with GTK v4.8 support.
fit = "Contain"

# The entries defined in this section will be passed to the session as environment variables when it is started
[env]
ENV_VARIABLE = "value"

[GTK]
# Whether to use the dark theme
application_prefer_dark_theme = true

# Cursor theme name
cursor_theme_name = "Adwaita"

# Font name and size
font_name = "NotoMono Nerd Font Mono 16"

# Icon theme name
icon_theme_name = "Arc-Icon-Theme"

# GTK theme name
theme_name = "Arc-Dark"

[commands]
# The command used to reboot the system
reboot = [ "systemctl", "reboot" ]

# The command used to shut down the system
poweroff = [ "systemctl", "poweroff" ]

```
