### ISSUE TITLE
Request: Include Example CSS File

### ISSUE THREAD

**Issue by DerGrumpf** [rharish101/ReGreet#116]
Hello,

I'm not really familiar with GTK CSS and can't find any good resource.
Might it be possible if an example.css should be included with the repo to help noobies like me?

Thanks :)

**Comment by medanimohamedakram** [comment]
@DerGrumpf , this tip might help you
So whatever gtk theme you like ,browse the theme folder, something like this path `<theme-folder>/gtk-4.0` and copy the file `gtk.css` and paste it in `/etc/greetd` then rename it `regreet.css`
run `regreet --demo` for testing and you should see that theme is applied

**Comment by natsukashiixo** [comment]
So far I've only found the class for the background of the main login box. This also controls the background for the clock widget though, so might not be what you want.
Doesn't control any of the input fields or buttons.
You can either do what @medanimohamedakram suggested and then put code like this at the top, or you can simply save this code as `regreet.css` in the appropriate location.

```css
/*try regreet override*/
frame.background {
  background-color: rgba(0, 0, 0, 0.1);
  border-radius: 6px;
  box-shadow: 12px 12px 24px rgba(0, 0, 0, 0.2);
}
```

I would also like to see a complete .css example someday, hopefully having some place to start inspires more people to play around with it and one day someone will PR a complete example.
