### ISSUE TITLE
Not loading theme or background image

### ISSUE THREAD

**Issue by TheSunCat** [rharish101/ReGreet#24]
Hi! I recently updated my system, including ReGreet, and it is no longer recognizing my theme or background image.
Here is my config:
```toml
cat /etc/greetd/regreet.toml                                                    
# SPDX-FileCopyrightText: 2022 Harish Rajagopal <harish.rajagopals@gmail.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Path to the background image
background = "/usr/share/backgrounds/greeter.jpg"

# How the background image covers the screen if the aspect ratio doesn't match
# Available values: "Fill", "Contain", "Cover", "ScaleDown"
# Refer to: https://docs.gtk.org/gtk4/enum.ContentFit.html
# NOTE: This is ignored if ReGreet isn't compiled with GTK v4.8 support.
background_fit = "Fill"

# The entries defined in this section will be passed to the session as environment variables when it is started
[env]
ENV_VARIABLE = "value"

[GTK]
# Whether to use the dark theme
application_prefer_dark_theme = true

# Cursor theme name
cursor_theme_name = "Catppuccin-Mocha-Dark"

# Font name and size
font_name = "Lexend Deca Regular 12"

# Icon theme name
icon_theme_name = "Adwaita"

# GTK theme name
theme_name = "Catppuccin-Mocha-Standard-Lavender-Dark"
```
There is a valid .jpg file at the path set as the background, which I will attach:
![greeter.jpg](https://user-images.githubusercontent.com/44881120/233791043-50e7009b-b8ca-4011-9216-558cdd2b136f.jpg)
ReGreet renders a fully white background, with what I assume is the default GTK theme (looks like light theme Adwaita), and the default Adwaita cursor.

Did I make a mistake in my configuration file?
