### ISSUE TITLE
ReGreet ignores config(or so it seems, at least)

### ISSUE THREAD

**Issue by Orest58008** [rharish101/ReGreet#29]
My config is
```toml
[background]
path = "/data/pictures/wallpapers/82072674_p0.png"

[env]
MOZ_ENABLE_WAYLAND=1

[GTK]
font_name = "Inter 16"
theme_name = "Catppuccin-Macchiato-Standard-Sapphire-Dark"
icon_theme_name = "Papirus-Dark"
cursor_theme_name = "posy-white"

[commands]
reboot = [ "systemctl", "reboot" ]
poweroff = [ "systemctl", "poweroff" ]
```
, but ReGreet seems to follow none of it. Logs show only this:
```
(regreet:371): Gtk-WARNING **: 21:32:36.877: Theme parser warning: <data>:6:17-18: Empty declaration
Failed to create //.cache for shader cache (Відмовлено у доступі)---disabling.
```

What could be the problem? The owner of `/etc/greetd` and all files inside is `greeter` and it has video permissions.
