### ISSUE TITLE
Custom greeting_msg doesn't display

### ISSUE THREAD

**Issue by Jademalo** [rharish101/ReGreet#83]
My greetd.toml is as follows;

```toml
[GTK]
application_prefer_dark_theme = true
theme_name = "catppuccin-macchiato-blue-standard"

[appearance]
greeting_msg = "Custom message test"

[background]
fit = "Cover"
path = "/nix/store/1m94safpiyfa47qlwrrjfgrxiws36fxy-original-x2.png"
```

For some reason the custom `greeting_msg` doesn't display, and it shows the standard `Welcome Back!` every time. All other settings are working, so it's clearly reading the toml and parsing the info. 
I've checked the code and I can't see anything obvious, so I've got no idea why it's not working. Currently running the latest commit, https://github.com/rharish101/ReGreet/commit/d2f45742706351843fec514e1fef8a37f70bfab2
