### ISSUE TITLE
Refactor the UI to be Elm architecture

### ISSUE THREAD

**Issue by max-ishere** [rharish101/ReGreet#85]
Here are the changes I propose:

1. Break up the widgets into separate structs. Right now all the widgets are this one giant widget
   template. Instead, if you take a look at the current UI there's:
   ```yaml
   - background
   - clock widget
   - reboot buttons
   - login form:
     - welcome message
     - either:
       session selection:
         - user field
         - session field
         - goto auth button
       auth:
         - selected user (const)
         - why no selected session? (const)
         - password field
         - auth button
   ```
   And some of these components are the same thing, just different labels, So there's not gonna be a
   separate type for each element.
2. Encode the state (session/auth screen, selected users) as a data structure and use it to render 
   the ui.
3. Move the business logic (greetd interface) into a trait and instead of doing `if demo {` Make a 
   `DemoGreeter`. Btw this demo greeter can respond with "*Demo mode password: pass*".

And this way the UI can be tested too by simply setting up the UI state struct, running the update() method and asserting the updated ui state.

--------

I can do the refactoring work and PR it in as small of increments as is managable for review. The steps would probably be as such (not sure about the order):
- Break up the UI into smaller components
- Use state to render the UI in `update()`.
These 2 might be too tightly coupled to separate tho...
